server:
  # 服务端口
  port: 8080
  name: nb-boot
  # 服务上线文
  context-path: nbboot
  # 公共接口
  public-url:
    - /api/v1/login
    - /api/v1/register


# 数据库配置
database:
  # mysql配置
  mysql:
    url: root:111111@tcp(localhost:3306)/nb_boot?charset=utf8mb4&parseTime=True&loc=Local
  # redis 配置
redis:
  host: localhost
  port: 6379
  password:

# log配置
log:
  level: debug

test: 123
  
