definitions:
  res.Result:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/user/:id:
    get:
      consumes:
      - application/x-json-stream
      description: :id 获取用户信息
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Result'
      summary: 通过用户id获取用户
      tags:
      - User Api
swagger: "2.0"
